serv:=$(lastword $(MAKECMDGOALS))

#include src/$(serv)/Makefile.config

CC:=clang
CFLAGS:=-std=gnu99 -D_MONGOOSE -DMG_TLS=MG_TLS_OPENSSL -D_TLS -D_TLS_TWOWAY
INCLUDES:=-I. -I.tools/include/apr-2 -I.tools/include/json-c
LIBS:=-L.tools/lib/apr-2 -L.tools/lib/json-c
LDFLAGS:=-lapr-2 -ljson-c -lssl -lcrypto
SRC:=mongoose.c libnetsrv.c netsrv.c

cmd:=$(CC) $(CFLAGS) $(EXTRA_CFLAGS) -o .tools/bin/$(serv) $(SRC) $(EXTRA_SRC) \
		 $(serv)/$(serv).c $(INCLUDES) $(EXTRA_INCLUDES) $(LIBS) $(EXTRA_LIBS) \
		 $(LDFLAGS) $(EXTRA_LDFLAGS)

all:

cert-ca:
	@chmod +x .tools/bin/cert_ca && .tools/bin/cert_ca

cert-client:
	@chmod +x .tools/bin/cert_client && .tools/bin/cert_client

cert-service:
	$(eval cmd:=.tools/bin/cert_service $(serv))
	@chmod +x .tools/bin/cert_service

service:
	$(eval cmd:=.tools/bin/service $(serv))
	@chmod +x .tools/bin/service

deb:
	$(eval cmd:=.tools/bin/deb $(serv))
	@chmod +x .tools/bin/deb

deps:
	$(eval cmd:=.tools/bin/deps $(serv))
	@chmod +x .tools/bin/deps

client:

mysql:
ifneq ($(mysql_driver),)
	$(eval cmd:=$(cmd) -d $(mysql_driver) -D $(mysql_conn_s))
endif

run:
	$(eval cmd:=LD_LIBRARY_PATH=$$LD_LIBRARY_PATH)
	$(eval cmd:=$(cmd):.tools/lib/apr-2:.tools/lib/json-c)
	$(eval cmd:=$(cmd) $(valgrind))
	$(eval cmd:=$(cmd) .tools/bin/$(serv) -h $(host) -p $(port) -s $(ssl_port))
	$(eval cmd:=$(cmd) -l .tools/var/log/$(serv).log)
	@chmod +x .tools/bin/$(serv)

debug:
	$(eval CFLAGS :=-g -D_DEBUG $(CFLAGS))

daemon:
	$(eval CFLAGS :=-D_DAEMON $(CFLAGS))

%:
	$(cmd)

clean:

.PHONY: all cert-ca cert-client cert-service service debug daemon mysql run deb deps client
