
APR_LIBS:=-L../apr/dist/lib
APR_INCLUDES:=-I../apr/dist/include/apr-2
JSON_C_LIBS:=-L../json-c/dist
JSON_C_INCLUDES:=-I../json-c -I../json-c/dist
MG_SRC:=../mongoose
MG_INCLUDES:=-I../mongoose

dist-apr:=../apr/dist/lib/libapr-2.*
dist-json-c:=../json-c/dist/libjson-c.*

dist-hello:=hello 0.0.1 8081 8082 8083
