
host:=0.0.0.0
port:=2310
ssl_port:=2443
mysql_driver:=mysql
mysql_conn_s:="host=127.0.0.1,port=3306,user=test,pass=test,dbname=test"
pgsql_driver:=
pgsql_conn_s:=
sqlite3_driver:=
sqlite3_conn_s:=
#valgrind:=valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes
